# Generated by Django 4.2 on 2023-04-11 00:47

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Information",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pragnancies", models.IntegerField()),
                ("Glucose", models.IntegerField()),
                ("BloodPressure", models.IntegerField()),
                ("SkinSickness", models.IntegerField()),
                ("Insulin", models.IntegerField()),
                ("BMI", models.IntegerField()),
                ("DiabestesPedfn", models.IntegerField()),
                ("Age", models.IntegerField(max_length=120)),
                ("Result", models.BooleanField(default=False)),
            ],
        ),
    ]
